### ISSUE TITLE
API key authentication

### ISSUE THREAD

**Issue by fredhastedt** [mhujer/ankiai#1]
Hi, 

Thanks for this nice idea. I have followed the steps in the github description, but ran into the following error (even though the API key is specified in the .env.local file):

```
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```

Have you encountered something similar as well? Or has OpenAI changed their API access in some way? 
Thanks for providing some guidance!

**Comment by mhujer** [comment]
Hi @fredhastedt! I've used the app myself a week ago and it worked fine so I don't think there was a change in the OpenAI API. My guess is that your `.env.local` is not loaded for some reason. You can try to add the key directly to existing `.env` to see if it helps.

I also recommend putting the key in apostrophes (actually I do it for all env variables), because the special characters (and maybe also the dash) may cause it not work as expected.

```env
OPENAI_API_KEY='sk-THISISMYOPENAIAPIKEY'
```

**Comment by fredhastedt** [comment]
Hi @mhujer. Thank you for getting back to me so quickly! I managed to fix the issue by purchasing some extra credits for my account - it seems like OpenAI did not recognize my old ones for some reason. 
I think your idea is really great, because I was never really bothered to manually find example sentences and other anki plug-ins rely on some database of sentences (which are by no means exhaustive at all). 

I was wondering if you were thinking about turning this into a plug-in at some stage? I think the only real hurdle to using this feature is when you are unfamiliar with coding / running code in your terminal. A direct plug-in where you would only have to provide the API-key, deck and language would be super cool!
As a last minor comment - could you update the README.md file to reflect the changes you introduced in your last commit, i.e., removing point 6. from the README.md?

**Comment by mhujer** [comment]
@fredhastedt Great that it works for you! For my English vocabulary I usually choose sentences from https://dictionary.cambridge.org/, but I couldn't find anything similar for Spanish, so I use ChatGPT for that. The only downside so far is that it sometimes gives you sentences for another meaning of the word, but overall the sentences are surprisingly useful.

I don't plan turning this into an Anki plugin, as I wrote it in TS because I'm not familiar with Python. But if you (or anyone else) want to port this to a real plugin, definitely go for it!

Thanks for the note regarding the readme, I will adjust it.

**Comment by fredhastedt** [comment]
@mhujer Yes, I agree that for languages other than English this tool is super useful!
Maybe if I find some free spare time, I might code this up for a plug-in in the future ;) 

In any case, thank you again for the help! Closing this issue now.

**Comment by fredhastedt** [comment]
Issue resolved.

**Comment by mhujer** [comment]
@fredhastedt FYI I converted it to a real Anki plugin.

**Comment by fredhastedt** [comment]
@mhujer Thanks for the update, will have a look over the weekend!
